let idiomaActual = "es";

const textos = {
  es: {
    consejotitulo: "Compra cuartos, compra muebles y arrastralos a los cuartos",
    consejoInventario: "Arrastra un objeto hacia un cuarto comprado.",
    consejoVenta: "Arrastra aquí muebles usados para venderlos",
    hotel: "Hotel",
    cuarto: "Cuarto",
    cama: "Cama",
    tvs: "TVs",
    lampara: "Lampara",
    sabanas: "Sábanas",
    internet: "Internet",
    clima: "Clima",
    cuadro: "Cuadros",
    fachada: "Fachada",

    catalogo: "Catálogo",
    comprar: "Comprar Cuarto",
    inventario: "Inventario",
    venta: "Venta De Usado",
    detalleCuarto: "Cuarto Seleccionado",
    empleados: "Empleados",
    materiales: "Almacen Materiales",
    indicadores: "Indicadores",
    finanzas: "Finanzas",
    prestamo: "Préstamo Bancario",
    clima: "Clima",
    controles: "Controles",
    movimiento: "Movimiento",
    climaDemanda: "Clima Y Demanda",
    planta: "Planta Luz",
    lavanderia: "Lavanderia",

    instrucciones: "Instrucciones",
    inicio: "inicio",
    avance: "Avanzar Hora",
    pausa: "Pausa",
    guardar: "Guardar Partida",
    ranking: "Mostrar Ranking",
    recuperar: "Recuperar Partida",

    agua: "Tanque De Agua",
    gas: "Tanque De Gas",
    basura: "Basura",
    drenaje: "Drenaje",

    comprarCuarto: "Comprar Cuarto",
    descComprarCuarto: "Desbloquea el siguiente cuarto disponible.",
    camaSencilla: "Cama Sencilla",
    descCamaSencilla: "Necesaria para rentar el cuarto.",
    camaKing: "Cama King",
    descCamaKing: "Aumento mucho el valor del cuarto.",
    tvSencilla: "Tv Sencilla",
    descTvSencilla: "Televisión básica para huéspedes.",
    tvHd: "TV HD",
    descTvHd: "Mejora la comodidad del cuarto.",
    tv5k: "TV 5K",
    descTv5k: "Television de lujo para clientes VIP.",
    lamparaSencilla: "Lampara Sencilla",
    descLamparaSencilla: "Iluminación básica.",
    lamparaElegante: "LamparaElegante",
    descLamparaElegante: "Da elégancia al cuarto.",
    alfombraBasica: "Alfombra Básica",
    descAlfombraBasica: "Decora el piso del cuarto.",
    alfombraFina: "Alfombra Fina",
    descAlfombraFina: "Sube el nivel del cuarto.",
    sabanasLimpias: "Sábanas Limpias",
    descSabanasLimpias: "Necesarias para rentar",
    sabanasPremium: "Sábanas Premium",
    descSabanasPremium: "Mejor descanso y más lujo.",
    extintor: "Extintor",
    descExtintor: "Seguridad básica del cuarto.",
    wifiBasico: "WiFi Básico",
    descWifiBasico: "Internet para huéspedes.",
    fibraOptica: "Fibra Optica",
    descFibraOptica: "Internet de alta velocidad.",
    aireAcondicionado: "Aire Acondicionado",
    descAireAcondicionado: "Mejora la comodidad.",
    climaInteligente: "Clima Inteligente",
    descClimaInteligente: "Sistema premium de climatización.",
    cuadroSencillo: "Cuadro Sencillo",
    descCuadroSencillo: "Decoración básica.",
    cuadroElegante: "Cuadro Elegante",
    descCuadroElegante: "Da estilo al cuarto.",
    artePremium: "Arte Premium",
    descArtePremium: "Decoración VIP.",
    plantaLuz: "Planta de Luz",
    descPlantaLuz: "Aumenta la capacidad eléctrica del hotel.",
    lavadora: "Lavadora",
    descLavadora: "Aumenta la capacidad de la lavandería.",
    elevador: "Elevador",
    descElevador: " Permite construir más pisos.",

    valorHotel: "Valor Hotel",
    dinero: "Dinero",
    dia: "Día",
    hora: "Hora",
    reputacion: "Reputación",
    ocupacion: "Ocupación",
    demanda: "Demanda",
  },

  en: {
    consejotitulo: "Buy rooms, buy furniture, and drag them into the rooms.",
    consejoInventario: "Drag an object to a purchased room.",
    consejoVenta: "Drag used furniture here to sell it.",
    hotel: "Hotel",
    cuarto: "Room",
    cama: "Bed",
    tvs: "TVs",
    lampara: "Lamp",
    sabanas: "Bed sheets",
    internet: "Internet",
    clima: "air conditioning",
    cuadro: "Paintings",
    fachada: "Facade",

    catalogo: "Catalog",
    comprar: "ShopBuy Room",
    inventario: "Inventory",
    venta: "Sale Of Used Items",
    detalleCuarto: "Selected Room",
    empleados: "Staff",
    materiales: "Supplies",
    indicadores: "Indicators",
    finanzas: "Finance – Last 10 Days",
    prestamo: "Bank Loan",
    clima: "Weather",
    controles: "Controls",
    movimiento: "Activity",
    climaDemanda: "Climate And Demand",
    planta: "Power Generator",
    lavanderia: "laundry",

    instrucciones: "Instructions",
    inicio: "Start",
    avance: "Advance The Time",
    pausa: "Pause",
    guardar: "Save Game",
    ranking: "Show Ranking",
    recuperar: "Retrieve Game",

    agua: "Water Tank",
    gas: "Gas Tank",
    basura: "Trash",
    drenaje: "Drainage",

    comprarCuarto: "Buy Room",
    descComprarCuarto: "Unlocks the next available room.",
    camaSencilla: "Single Bed",
    descCamaSencilla: "Necessary to rent the room.",
    camaKing: "King Bed",
    descCamaKing: "It significantly increased the value of the room.",
    tvSencilla: "Basic TV",
    descTvSencilla: "Basic television for guests.",
    tvHd: "HD TV",
    descTvHd: "It improves the comfort of the room.",
    tv5k: "5K TV",
    descTv5k: "Luxury television for VIP clients.",
    lamparaSencilla: "Simple Lamp",
    descLamparaSencilla: "Basic lighting.",
    lamparaElegante: "Elegant Lamp",
    descLamparaElegante: "It adds elegance to the room.",
    alfombraBasica: "Basic Rug",
    descAlfombraBasica: "Decorate the room's floor.",
    alfombraFina: "Fine Rug",
    descAlfombraFina: "Elevate the level of the room.",
    sabanasLimpias: "Clean Sheets",
    descSabanasLimpias: "Required for renting.",
    sabanasPremium: "Premium Sheets",
    descSabanasPremium: "Better rest and more luxury.",
    extintor: "Extinguisher",
    descExtintor: "Basic room safety.",
    wifiBasico: "Basic Wi-Fi",
    descWifiBasico: "Guest internet.",
    fibraOptica: "Optical fiber",
    descFibraOptica: "High-speed internet.",
    aireAcondicionado: "Air-conditioning",
    descAireAcondicionado: "Improves comfort.",
    climaInteligente: "Smart Climate",
    descClimaInteligente: "Premium climate control system.",
    cuadroSencillo: "Simple Chart",
    descCuadroSencillo: "Basic decoration.",
    cuadroElegante: "Elegant Picture",
    descCuadroElegante: "DIt adds style to the room.",
    artePremium: "Premium Art",
    descArtePremium: "VIP décor.",
    plantaLuz: "Generator",
    descPlantaLuz: "It increases the hotel's electrical capacity.",
    lavadora: "Washing machine",
    descLavadora: "Increases the laundry capacity.",
    elevador: "Elevador",
    descElevador: "It allows for the construction of more floors.",

    valorHotel: "Hotel Value",
    dinero: "Money",
    dia: "Day",
    hora: "Time",
    reputacion: "Reputation",
    ocupacion: "Occupancy",
    demanda: "Demand",
  },
};
